import os
from datetime import datetime, timezone
from typing import Any, Dict

from fpdf import FPDF

from backend.config import UPLOAD_DIR


def _sanitize(text: str) -> str:
    replacements = {
        "\u2014": "-",
        "\u2013": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2026": "...",
        "\u2022": "*",
        "\u00b7": "*",
        "\u2010": "-",
        "\u2011": "-",
        "\u2012": "-",
        "\u2015": "-",
        "\u2032": "'",
        "\u2033": '"',
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", errors="replace").decode("latin-1")


class InspectionPDF(FPDF):
    BRAND_DARK = (15, 23, 42)
    BRAND_PRIMARY = (37, 99, 235)
    BRAND_ACCENT = (234, 179, 8)
    WHITE = (255, 255, 255)
    LIGHT_BG = (241, 245, 249)
    TEXT_COLOR = (30, 41, 59)
    BORDER_COLOR = (203, 213, 225)

    def header(self):
        self.set_fill_color(*self.BRAND_DARK)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*self.WHITE)
        self.set_xy(10, 3)
        self.cell(0, 12, "AI FIELD INSPECTOR", ln=False)
        self.set_font("Helvetica", "", 9)
        self.set_xy(150, 5)
        self.cell(0, 8, "Automated Inspection Report", ln=True)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by AI Field Inspector  |  {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*self.BRAND_PRIMARY)
        self.cell(0, 10, _sanitize(title), ln=True)
        self.set_draw_color(*self.BRAND_PRIMARY)
        self.line(self.get_x(), self.get_y(), 200, self.get_y())
        self.ln(3)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.TEXT_COLOR)
        self.multi_cell(0, 6, _sanitize(text))
        self.ln(2)

    def badge(self, label: str, color: tuple):
        x = self.get_x()
        y = self.get_y()
        w = self.get_string_width(label) + 8
        self.set_fill_color(*color)
        self.set_text_color(*self.WHITE)
        self.set_font("Helvetica", "B", 9)
        self.rect(x, y, w, 7, "F")
        self.set_xy(x + 1, y + 0.5)
        self.cell(w - 2, 6, _sanitize(label), ln=False)
        self.set_xy(x + w + 3, y)

    def severity_color(self, severity: str) -> tuple:
        return {
            "critical": (220, 38, 38),
            "high": (234, 88, 12),
            "medium": (234, 179, 8),
            "low": (34, 197, 94),
        }.get(severity.lower(), (100, 100, 100))


def generate_pdf(report: Dict[str, Any], image_name: str = "inspection_image.jpg", image_path: str | None = None, processing_time: float | None = None) -> str:
    os.makedirs(UPLOAD_DIR, exist_ok=True)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    pdf_filename = f"inspection_report_{timestamp}.pdf"
    pdf_path = os.path.join(UPLOAD_DIR, pdf_filename)

    pdf = InspectionPDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, _sanitize(f"Image: {image_name}   |   Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"), ln=True)
    pdf.ln(4)

    risk = report.get("overall_risk_level", "medium").upper()
    risk_color = pdf.severity_color(risk.lower())
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*pdf.TEXT_COLOR)
    pdf.cell(40, 8, "Overall Risk: ", ln=False)
    pdf.badge(risk, risk_color)
    pdf.ln(12)

    pdf.section_title("1. Executive Summary")
    pdf.body_text(report.get("summary", "No summary available."))

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*pdf.TEXT_COLOR)
    pdf.cell(0, 6, "Model Used:", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, _sanitize("MobileNetV2 CNN classifier; findings summarized by Gemini 2.0 Flash LLM."), ln=True)
    if processing_time is not None:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*pdf.TEXT_COLOR)
        pdf.cell(30, 6, "Processing Time: ", ln=False)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, _sanitize(f"{processing_time}s"), ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*pdf.TEXT_COLOR)
    pdf.cell(0, 7, "Severity Legend:", ln=True)
    pdf.set_font("Helvetica", "", 9)
    legend_items = [
        ("Low", (34, 197, 94), "Cosmetic"),
        ("Medium", (234, 179, 8), "Monitor"),
        ("High", (234, 88, 12), "Urgent"),
        ("Critical", (220, 38, 38), "Immediate action"),
    ]
    for label, color, desc in legend_items:
        pdf.badge(label, color)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*pdf.TEXT_COLOR)
        pdf.cell(30, 7, _sanitize(f" - {desc}"), ln=False)
        pdf.cell(5, 7, "", ln=False)
    pdf.ln(8)

    if image_path and os.path.exists(image_path):
        try:
            pdf.section_title("2. Inspection Image")
            available_w = 190
            pdf.image(image_path, x=10, w=min(available_w, 170), h=0)
            pdf.ln(6)
        except Exception:
            pass

    pdf.section_title("3. Detailed Findings")
    findings = report.get("findings", [])

    if findings:
        pdf.set_fill_color(*pdf.BRAND_DARK)
        pdf.set_text_color(*pdf.WHITE)
        pdf.set_font("Helvetica", "B", 9)
        col_w = [10, 30, 22, 22, 106]
        headers = ["#", "Type", "Severity", "Conf.", "Explanation & Action"]
        for i, h in enumerate(headers):
            pdf.cell(col_w[i], 8, h, border=1, fill=True)
        pdf.ln()

        pdf.set_text_color(*pdf.TEXT_COLOR)
        pdf.set_font("Helvetica", "", 8)

        for f in findings:
            fid = str(f.get("id", ""))
            ftype = f.get("damage_type", "").capitalize()
            fsev = f.get("severity", "").capitalize()
            fconf = f"{f.get('confidence', 0):.0%}"
            fexpl = f.get("explanation", "")
            faction = f.get("recommended_action", "")
            combined = _sanitize(f"{fexpl} Action: {faction}")

            row_h = max(8, pdf.get_string_width(combined) / col_w[4] * 5 + 6)

            if pdf.get_y() + row_h > 270:
                pdf.add_page()

            y_before = pdf.get_y()
            x_start = pdf.get_x()
            pdf.cell(col_w[0], row_h, _sanitize(fid), border=1)
            pdf.cell(col_w[1], row_h, _sanitize(ftype), border=1)
            pdf.cell(col_w[2], row_h, _sanitize(fsev), border=1)
            pdf.cell(col_w[3], row_h, _sanitize(fconf), border=1)

            x_mc = pdf.get_x()
            pdf.multi_cell(col_w[4], 5, _sanitize(combined), border=1)
            actual_h = pdf.get_y() - y_before

            if actual_h > row_h:
                pdf.set_y(y_before + actual_h)

        pdf.ln(4)
    else:
        pdf.body_text("No findings to report.")

    pdf.section_title("4. Inspection Checklist")
    checklist = report.get("checklist", [])
    for item in checklist:
        status = item.get("status", "pending")
        icon = "[  ]" if status == "pending" else "[X]"
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*pdf.TEXT_COLOR)
        pdf.cell(0, 7, _sanitize(f"  {icon}  {item.get('item', '')}"), ln=True)
    pdf.ln(4)

    pdf.section_title("5. Safety Recommendations")
    safety = report.get("safety_notes", [])
    for i, note in enumerate(safety, 1):
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*pdf.TEXT_COLOR)
        pdf.cell(0, 7, _sanitize(f"  {i}. {note}"), ln=True)
    pdf.ln(4)

    pdf.section_title("6. Responsible AI Disclaimer")
    ai_note = report.get(
        "responsible_ai_note",
        "This report is AI-generated to assist human inspectors. "
        "All findings should be validated by a qualified professional. "
        "AI assists — it does not replace — expert judgment."
    )
    pdf.set_fill_color(*pdf.LIGHT_BG)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(0, 6, _sanitize(ai_note), fill=True)

    pdf.output(pdf_path)
    return pdf_path
